# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  username: adel
  password: password
  host: localhost
  port: 5432
  min_messages: notice
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rahma_app_development 


staging:
  <<: *default
  database: rahma_app_test
  
production:
  <<: *default
  database: rahma_app_production